backend:
  name: git-gateway
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth

site_url: https://vgbcglobal.netlify.app
logo_url: /images/logo-removebg-preview.png

# Media settings
media_folder: "images/uploads"
public_folder: "/images/uploads"

# Editorial workflow for review process
publish_mode: editorial_workflow

# Custom settings
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

# Collections
collections:
  # Static Sections
  - name: "sections"
    label: "Website Sections"
    description: "Manage static HTML sections of the website"
    files:
      - label: "Hero Section"
        name: "hero"
        file: "pages/hero.html"
        fields:
          - { label: "HTML Content", name: "body", widget: "code", default_language: "html" }

      - label: "About Section"
        name: "about"
        file: "pages/about.html"
        fields:
          - { label: "HTML Content", name: "body", widget: "code", default_language: "html" }

      - label: "Services Section"
        name: "services"
        file: "pages/services.html"
        fields:
          - { label: "HTML Content", name: "body", widget: "code", default_language: "html" }

      - label: "Ecosystem (New Services)"
        name: "newservices"
        file: "pages/newservices.html"
        fields:
          - { label: "HTML Content", name: "body", widget: "code", default_language: "html" }

      - label: "Business Network"
        name: "businessNetwork"
        file: "pages/business-network.html"
        fields:
          - { label: "HTML Content", name: "body", widget: "code", default_language: "html" }

      - label: "Contact Section"
        name: "contact"
        file: "pages/contact.html"
        fields:
          - { label: "HTML Content", name: "body", widget: "code", default_language: "html" }

      - label: "Footer"
        name: "footer"
        file: "pages/footer.html"
        fields:
          - { label: "HTML Content", name: "body", widget: "code", default_language: "html" }

  # News Articles
  - name: "news"
    label: "News Articles"
    description: "Manage news and blog articles"
    folder: "content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Publish Date", name: "date", widget: "datetime", required: true }
      - { label: "Author", name: "author", widget: "string", default: "VGBC Team" }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Excerpt", name: "excerpt", widget: "text", required: false }
      - { label: "Category", name: "category", widget: "select", options: ["Business", "Translation", "News", "Events"], required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Content", name: "body", widget: "markdown", required: true }

  # Testimonials
  - name: "testimonials"
    label: "Customer Testimonials"
    description: "Manage customer testimonials and reviews"
    folder: "content/testimonials"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Customer Name", name: "name", widget: "string", required: true }
      - { label: "Company", name: "company", widget: "string", required: false }
      - { label: "Position", name: "position", widget: "string", required: false }
      - { label: "Testimonial", name: "content", widget: "text", required: true }
      - { label: "Rating", name: "rating", widget: "number", min: 1, max: 5, default: 5 }
      - { label: "Customer Image", name: "image", widget: "image", required: false }
      - { label: "Language", name: "language", widget: "select", options: ["vi", "en", "zh"], default: "vi" }

  # Interpreters & Staff
  - name: "interpreters"
    label: "Interpreters & Staff"
    description: "Manage team members and interpreters"
    folder: "content/interpreters"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Full Name", name: "name", widget: "string", required: true }
      - { label: "Position", name: "position", widget: "string", required: true }
      - { label: "Bio", name: "bio", widget: "text", required: true }
      - { label: "Email", name: "email", widget: "string", required: false }
      - { label: "Phone", name: "phone", widget: "string", required: false }
      - { label: "Languages", name: "languages", widget: "list", required: true }
      - { label: "Experience Years", name: "experience", widget: "number", required: false }
      - { label: "Photo", name: "image", widget: "image", required: false }
      - { label: "Specializations", name: "specializations", widget: "list", required: false }

  # Translations
  - name: "translations"
    label: "Language Translations"
    description: "Manage multi-language translations"
    files:
      - label: "Vietnamese (vi)"
        name: "vi"
        file: "translations/vi.json"
        fields:
          - { label: "Vietnamese JSON", name: "body", widget: "code", default_language: "json" }

      - label: "English (en)"
        name: "en"
        file: "translations/en.json"
        fields:
          - { label: "English JSON", name: "body", widget: "code", default_language: "json" }

      - label: "Chinese (zh)"
        name: "zh"
        file: "translations/zh.json"
        fields:
          - { label: "Chinese JSON", name: "body", widget: "code", default_language: "json" }
