backend:
  name: git-gateway
  branch: main          # hoặc master nếu repo cũ
  base_url: https://api.netlify.com
  auth_endpoint: auth

site_url: https://vgbcglobal.netlify.app
logo_url: /images/logo-removebg-preview.png

media_folder: "images/uploads"
public_folder: "/images/uploads"

publish_mode: editorial_workflow

collections:

  # --- 1. Static Sections (HTML trong /pages) ---
  - name: "sections"
    label: "Website Sections"
    files:
      - label: "Hero Section"
        name: "hero"
        file: "pages/hero.html"
        fields:
          - { label: "HTML Content", name: "body", widget: "code", default_language: "html" }

      - label: "About Section"
        name: "about"
        file: "pages/about.html"
        fields:
          - { label: "HTML Content", name: "body", widget: "code", default_language: "html" }

      - label: "Services Section"
        name: "services"
        file: "pages/services.html"
        fields:
          - { label: "HTML Content", name: "body", widget: "code", default_language: "html" }

      - label: "Ecosystem (New Services)"
        name: "newservices"
        file: "pages/newservices.html"
        fields:
          - { label: "HTML Content", name: "body", widget: "code", default_language: "html" }

      - label: "Business Network"
        name: "businessNetwork"
        file: "pages/business-network.html"
        fields:
          - { label: "HTML Content", name: "body", widget: "code", default_language: "html" }

      - label: "Contact Section"
        name: "contact"
        file: "pages/contact.html"
        fields:
          - { label: "HTML Content", name: "body", widget: "code", default_language: "html" }

      - label: "Footer"
        name: "footer"
        file: "pages/footer.html"
        fields:
          - { label: "HTML Content", name: "body", widget: "code", default_language: "html" }

  # --- 2. News Articles (dạng Markdown trong /news) ---
  - name: "news"
    label: "News Articles"
    folder: "news"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: "VGBC Team" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  # --- 3. Translations (đa ngôn ngữ JSON) ---
  - name: "translations"
    label: "Language Translations"
    files:
      - label: "Vietnamese (vi)"
        name: "vi"
        file: "translations/vi.json"
        fields:
          - { label: "Vietnamese JSON", name: "body", widget: "code", default_language: "json" }

      - label: "English (en)"
        name: "en"
        file: "translations/en.json"
        fields:
          - { label: "English JSON", name: "body", widget: "code", default_language: "json" }

      - label: "Chinese (zh)"
        name: "zh"
        file: "translations/zh.json"
        fields:
          - { label: "Chinese JSON", name: "body", widget: "code", default_language: "json" }
