backend:
  name: git-gateway
  branch: main          # hoặc "master" nếu repo cũ
  repo: Tien0404/web-cms  # thay bằng repo GitHub của bạn
  base_url: https://api.netlify.com
  auth_endpoint: auth

media_folder: "images/uploads"     # nơi lưu ảnh thật trong repo
public_folder: "/images/uploads"   # đường dẫn ảnh trên site

site_url: https://https://vgbcglobal.netlify.app/   # thay bằng domain thật của bạn
logo_url: /images/logo-removebg-preview.png

publish_mode: editorial_workflow   # cho phép duyệt trước khi publish

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

collections:

  # 🏠 HERO SECTION
  - name: "hero"
    label: "Hero Section"
    file: "data/content.json"
    editor:
      preview: false
    fields:
      - label: "Hero"
        name: "hero"
        widget: "object"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "text" }
          - { label: "Button: Services", name: "btnServices", widget: "string" }
          - { label: "Button: Get Quote", name: "btnQuote", widget: "string" }

  # 🧭 ABOUT SECTION
  - name: "about"
    label: "About Section"
    file: "data/content.json"
    editor:
      preview: false
    fields:
      - label: "About"
        name: "about"
        widget: "object"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }

  # 💼 SERVICES SECTION
  - name: "services"
    label: "Services Section"
    file: "data/content.json"
    editor:
      preview: false
    fields:
      - label: "Services"
        name: "services"
        widget: "list"
        summary: "{{fields.name}}"
        fields:
          - { label: "Service Name", name: "name", widget: "string" }
          - { label: "Description", name: "desc", widget: "text" }
          - { label: "Image", name: "image", widget: "image", required: false }

  # 🌐 BUSINESS NETWORK
  - name: "businessNetwork"
    label: "Business Network Section"
    file: "data/content.json"
    editor:
      preview: false
    fields:
      - label: "Business Network"
        name: "businessNetwork"
        widget: "object"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "text" }
          - label: "Partners"
            name: "partners"
            widget: "list"
            fields:
              - { label: "Category", name: "title", widget: "string" }
              - { label: "Description", name: "desc", widget: "text" }
              - { label: "Icon", name: "icon", widget: "image", required: false }
          - label: "Success Stories"
            name: "successStories"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "desc", widget: "text" }
              - { label: "Image", name: "image", widget: "image", required: false }

  # 🧩 ECOSYSTEM / NEW SERVICES
  - name: "newservices"
    label: "Ecosystem Section (New Services)"
    file: "data/content.json"
    editor:
      preview: false
    fields:
      - label: "Ecosystem"
        name: "newservices"
        widget: "object"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "text" }
          - label: "Service Categories"
            name: "categories"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Description", name: "desc", widget: "text" }
              - label: "Sub-items"
                name: "items"
                widget: "list"
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Detail", name: "desc", widget: "text" }

  # 📰 NEWS COLLECTION
  - name: "news"
    label: "News Articles"
    folder: "data/news"
    create: true
    extension: "json"
    format: "json"
    slug: "{{slug}}"
    identifier_field: "title"
    summary: "{{title}} — {{date}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Author", name: "author", widget: "string", default: "VGBC Team" }
      - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Cover Image", name: "image", widget: "image" }
      - { label: "Content", name: "content", widget: "markdown" }

  # 🌍 TRANSLATIONS (Đa ngôn ngữ)
  - name: "translations"
    label: "Translations (i18n)"
    files:
      - label: "Vietnamese"
        name: "vi"
        file: "translations/vi.json"
        fields:
          - { label: "Language JSON (vi)", name: "body", widget: "code", default_language: "json" }
      - label: "English"
        name: "en"
        file: "translations/en.json"
        fields:
          - { label: "Language JSON (en)", name: "body", widget: "code", default_language: "json" }
      - label: "Chinese"
        name: "zh"
        file: "translations/zh.json"
        fields:
          - { label: "Language JSON (zh)", name: "body", widget: "code", default_language: "json" }
