backend:
  name: git-gateway
  branch: main          # hoặc "master" nếu repo cũ
  repo: Tien0404/web-cms  # thay bằng repo GitHub của bạn
  base_url: https://api.netlify.com
  auth_endpoint: auth

media_folder: "images/uploads"     # nơi lưu ảnh thật trong repo
public_folder: "/images/uploads"   # đường dẫn ảnh trên site

site_url: https://vgbcglobal.netlify.app/   # thay bằng domain thật của bạn
logo_url: /images/logo-removebg-preview.png

publish_mode: editorial_workflow   # cho phép duyệt trước khi publish

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

collections:

  # HERO SECTION
  - name: "hero"
    label: "Hero Section"
    files:
      - label: "Hero Content"
        name: "hero"
        file: "data/content.json"
        fields:
          - label: "Hero"
            name: "hero"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Subtitle", name: "subtitle", widget: "text" }
              - { label: "Button (Services)", name: "btnServices", widget: "string" }
              - { label: "Button (Quote)", name: "btnQuote", widget: "string" }

  # ABOUT SECTION
  - name: "about"
    label: "About Section"
    files:
      - label: "About Content"
        name: "about"
        file: "data/content.json"
        fields:
          - label: "About"
            name: "about"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }

  # SERVICES SECTION
  - name: "services"
    label: "Services Section"
    files:
      - label: "Services List"
        name: "services"
        file: "data/content.json"
        fields:
          - label: "Services"
            name: "services"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Description", name: "desc", widget: "text" }

  # BUSINESS NETWORK SECTION
  - name: "businessNetwork"
    label: "Business Network Section"
    files:
      - label: "Business Network Content"
        name: "businessNetwork"
        file: "data/content.json"
        fields:
          - label: "Business Network"
            name: "businessNetwork"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Subtitle", name: "subtitle", widget: "text" }

  # ECOSYSTEM SECTION
  - name: "newservices"
    label: "Ecosystem Section"
    files:
      - label: "Ecosystem Content"
        name: "newservices"
        file: "data/content.json"
        fields:
          - label: "Ecosystem"
            name: "newservices"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Subtitle", name: "subtitle", widget: "text" }

  # NEWS (vẫn giữ dạng folder)
  - name: "news"
    label: "News Articles"
    folder: "data/news"
    create: true
    extension: "json"
    format: "json"
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Cover Image", name: "image", widget: "image" }
      - { label: "Content", name: "content", widget: "markdown" }

  # TRANSLATIONS
  - name: "translations"
    label: "Translations (i18n)"
    files:
      - label: "Vietnamese"
        name: "vi"
        file: "translations/vi.json"
        fields:
          - { label: "Vietnamese JSON", name: "body", widget: "code", default_language: "json" }
      - label: "English"
        name: "en"
        file: "translations/en.json"
        fields:
          - { label: "English JSON", name: "body", widget: "code", default_language: "json" }
      - label: "Chinese"
        name: "zh"
        file: "translations/zh.json"
        fields:
          - { label: "Chinese JSON", name: "body", widget: "code", default_language: "json" }
